version: '2'
services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=2.0.8
        - SHA256=d9594c4d552a3e4f965b188a4774da8c8b010fc23ddb0efc63b1d94818dde1ca
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - khuh-factorio:/factorio
    networks:
      - homeserverweb
    environment:
      - PUID=0
      - PGID=0
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34198
#      - PRESET=deathworld
#      - ADDR=::1
networks:
  homeserverweb:
    external: true
volumes:
  khuh-factorio:
    external: true